spring:
  data:
    mongodb:
      database: books
  mongodb:
    embedded:
      version: 3.5.5

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.asamofalov.hw08.mongock.changelog
